"""initial schema

Revision ID: ae21f0e1e5f4
Revises: 
Create Date: 2026-07-18 15:01:40.835440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae21f0e1e5f4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_profiles',
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('competitors', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    with op.batch_alter_table('business_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_business_profiles_domain'), ['domain'], unique=False)

    op.create_table('pipeline_runs',
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('profile_uuid', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('queries_discovered', sa.Integer(), nullable=True),
    sa.Column('queries_scored', sa.Integer(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_uuid'], ['business_profiles.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('discovered_queries',
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('profile_uuid', sa.String(length=36), nullable=False),
    sa.Column('run_uuid', sa.String(length=36), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('query_intent', sa.String(length=32), nullable=True),
    sa.Column('estimated_search_volume', sa.Integer(), nullable=True),
    sa.Column('competitive_difficulty', sa.Integer(), nullable=True),
    sa.Column('opportunity_score', sa.Float(), nullable=True),
    sa.Column('domain_visible', sa.Boolean(), nullable=True),
    sa.Column('visibility_position', sa.Integer(), nullable=True),
    sa.Column('visibility_status', sa.String(length=16), nullable=True),
    sa.Column('discovered_at', sa.DateTime(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_uuid'], ['business_profiles.uuid'], ),
    sa.ForeignKeyConstraint(['run_uuid'], ['pipeline_runs.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('content_recommendations',
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('profile_uuid', sa.String(length=36), nullable=False),
    sa.Column('query_uuid', sa.String(length=36), nullable=False),
    sa.Column('content_type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('target_keywords', sa.JSON(), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_uuid'], ['business_profiles.uuid'], ),
    sa.ForeignKeyConstraint(['query_uuid'], ['discovered_queries.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('content_recommendations')
    op.drop_table('discovered_queries')
    op.drop_table('pipeline_runs')
    with op.batch_alter_table('business_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_business_profiles_domain'))

    op.drop_table('business_profiles')
    # ### end Alembic commands ###
